### PR TITLE
Fixing link & adding export volume

### PR DESCRIPTION
**Pull request by Pyrrha**
Hello

This PR isn't fixing reported issue.

Changes in this pull request:
- Updating firefly-iii.env to match main repository example file
- ~~Fix env filename to existing firefly-iii.env~~
- ~~Creating and adding export directory to mounted volumes~~

Now the project is more up-to-date with the main repository, ~~the docker-compose file use the existing provided env file~~, ~~and adds missing export directory~~.

@JC5

### CODE REVIEW

**Comment by Pyrrha** [comment]
Sorry, I just saw #11 and it's against what I just suggest.

The force-push cancels the adding of export directory that was previously deleted.

Thanks for your work!

**Comment by JC5** [comment]
Nice. Could you undo the rename in docker-compose.yml though? Downloading + renaming the file makes people aware of the file's existence and saves me a lot of questions.

**Comment by Pyrrha** [comment]
Done: the only diff is the add of 2 lines of comments finally.

**Comment by JC5** [comment]
Nice work regardless! :+1:

**Pull request merged**
