### PR TITLE
de-duplicate database user/password information

### PR DESCRIPTION
**Pull request by Robert-Obermeier**
Changes in this pull request:

- remove duplicate authentication information from compose file

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
That's not a bad idea, but where does the environment variable value come from?

**Comment by Obbi89** [comment]
Oh yeah that is a detail that is not that obvious about docker-compose.
Docker compose reads the .env file and you can use all defined variables from there within your docker-compose.yml.

If you have services you can even just pass them through like that:

```yaml
services:
  super:
    environment:
       - FOO
       - BAR
```

**Comment by JC5** [comment]
I see what you mean. That also means that I can't merge this change, because I can't guarantee that people will use ".env" and I know for a fact that some people don't.

**Comment by JC5** [comment]
Which means I'm sorry @Robert-Obermeier, but I must decline your contribution. I like what you changed though. It's easier and quicker for a lot of users. But it would also break Firefly III for another group so it's a trade-off.

**Comment by Obbi89** [comment]
Oh yeah and I had created that from my work account (I realize now) which was an error anyways. I'm closing this and maybe suggest an edit or hint in the documentation later :)

**Comment by JC5** [comment]
Sounds great!

**Comment by SuperSandro2000** [comment]
Also docker-compose uses real environment variables as a fallback.

**Pull request closed without merging**
