### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Changes in this pull request: Just some little improvements :)

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Thanks. Keep in mind that wait-for-it.sh is from another library and is going to be overwritten anyway, so those changes may not keep.

**Comment by SuperSandro2000** [comment]
> Keep in mind that wait-for-it.sh is from another library and is going to be overwritten anyway, so those changes may not keep.

Didn't know that but they where very small anyway. Thanks for the info.

**Comment by JC5** [comment]
I have reversed your changes and welcome your input: https://github.com/firefly-iii/firefly-iii/issues/3062

**Comment by SuperSandro2000** [comment]
I don't think this is my fault cause all my changes where purely esthetic and shouldn't change any function.

**Comment by SuperSandro2000** [comment]
I am 100% sure and tested it that this change caused the crash https://github.com/firefly-iii/docker/blob/723e124c9f70daa9f99fb51899f9e28e85b87432/scripts/entrypoint.sh

If you set ``-u`` all vars need to be set and some are not. You can use fallbacks like ``${VAR:-"fallback"}``.

See https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#The-Set-Builtin

Quote:
``
-u
Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit.
``

This PR should fix it: https://github.com/firefly-iii/docker/pull/4

PS:
``set -euo pipefail`` needs some more testing cause right now some command fail normally and if you add this line the container will abort mid way trough the entrypoint.

Let me know if you need some help with that. I am experienced with such tasks 😉 https://github.com/keycloak/keycloak-containers/pull/235

**Pull request merged**
